### ISSUE TITLE
Missing update after changing favourite beer

### ISSUE THREAD

**Issue by michael-k** [OpenBeerMap/OpenBeerMap.github.io#41] opened 2015-01-30 10:22 UTC
Refers to: http://nlehuby.github.io/

1. Go to a bar that serves guinness and open its *“Edit bar information”* dialog.
2. Click on *“Customize”*, remove all beers and add them (or at least guinness) again.
3. The *“Edit bar information”* dialog is not updated and guinness doesn't seem to be served.
4. Close the *“Edit bar information”* dialog and open it again. All is back to normal as in step 1.

Another issue that appears after this is, that there is no way to remove the guinness bars from the map. Those displayed in step 1 will always be visible until you reload the page. In the last image you can see that guinness (on the right side) is not selected, but the bar is still shown on the map.

![1](https://cloud.githubusercontent.com/assets/152008/5974067/4b170238-a870-11e4-84dc-a469da775147.png)
![2](https://cloud.githubusercontent.com/assets/152008/5974069/4b41cf68-a870-11e4-97f0-87c00e481b2d.png)
![3](https://cloud.githubusercontent.com/assets/152008/5974068/4b41ab64-a870-11e4-828b-9bc09fbae9db.png)
![4](https://cloud.githubusercontent.com/assets/152008/5974070/4b41f31c-a870-11e4-92a9-1edb045cf325.png)

**Comment by nlehuby** [comment] 2015-01-30 12:04
Hi Mikael,

thank you for your feedback !

I cannot reproduce your bug at all ... Did you test the very last version on nlehuby.github.io ? 
I've seen bugs like this in previous versions of the app, but it seems to me that they all have been fixed by now.

Here is what i can see :

Go to a bar that serves guinness and open its edit bar information dialog
> ok
![Go to a bar that serves Guinness](https://lut.im/KMDBW4N3/EHHBS5Fj)
![open the edit bar dialog](https://lut.im/2wRoyrVQ/DUCu4cK4)

Click on Customize, remove all beers, and them back
> ok. The bars that serves Guinness already displayed on the map disappeared. 
![remove all beers](https://lut.im/lXEq8pVx/qZ4zgyaQ)
Guinness is displayed twice in the edit bar dialog : one is selected, the other not (data issue with the capital letters ; does not impact the beer data registered to OSM).
![final result](https://lut.im/ibayqTM5/2xFytaH9)

Please let me know !

**Comment by michael-k** [comment] 2015-01-30 12:44
I did test it with http://nlehuby.github.io on Firefox 35.0.1

> The bars that serves Guinness already displayed on the map disappeared.

I observed that it works sometimes, but doesn't always.

1. Open http://nlehuby.github.io (hard reload)
2. Select only layer “Guinness”
3. Open bar information and keep all dialogs open
![6](https://cloud.githubusercontent.com/assets/152008/5975704/a26c9c28-a884-11e4-9012-dbe3c2d697cd.png)
4. Customize → Clear list; see how the guinness layer has disappeared, but not the layer links on the right
![7](https://cloud.githubusercontent.com/assets/152008/5975715/d7297c2e-a884-11e4-8186-18eb0a1a2b2c.png)
5. Close the bar information (only leftover dialog). Select layer “guinness”, open bar information and keep everything open as in step 3 (first image).
6. Customize → add “guinness”, now it is displayed twice (without any data issue regarding capital letters; OSM database: `brewery = chouffe;guinness;affligem;tripel_karmeliet;kwak;san miguel`)
![9](https://cloud.githubusercontent.com/assets/152008/5975792/d1abde94-a885-11e4-9ce6-e216248450da.png)
7. Clear list; see how the layer didn't disappear
![10](https://cloud.githubusercontent.com/assets/152008/5975806/f482095c-a885-11e4-93d1-752a43dbb1a2.png)


> Guinness is displayed twice in the edit bar dialog : one is selected, the other not (data issue with the capital letters ; does not impact the beer data registered to OSM).

As you can see above, I also found ways to display it twice without any data issues.

**Comment by nlehuby** [comment] 2015-01-30 13:20
Ok, got it.

TODO : 
* remove the cancel button
* refresh beers list in the control + refresh beers list in the edit bar modal when an action is performed with the favourite beers
* create another issue about the beer displayed twice

**Comment by nlehuby** [comment] 2015-02-05 12:54
I've patched #40 
Could you please click around to check if you can still reproduce ?

**Comment by michael-k** [comment] 2015-02-05 13:45
The removed and then added beer still pops up twice in “Bar edition” → “Available draft beers”. The correct list is displayed after reopening the dialog.

Other than that, it works. :+1: 

Here are some improvements to “Customize” I suggest:
- The “Save” button should be renamed to “Close”. It should be on the right. (This is where – in my experience – close buttons are in general.)
- The “Clear list” button should be on the left, because the list is on the left (at least on wide displays).
- The “Add favourite beer” input should add the beer on enter (key event). (Same for “Add beer” in “Bar edition”).
I could've created issues for all of them, but the changes necessary seemed to small and are related to the changes made in regard of this issue.

**Closed** 2015-02-08 16:50 UTC
